### ISSUE TITLE
How to restore a KUP backup?

### ISSUE THREAD

**Issue by akj010** [spersson/Kup#100]
I used `kup-backup` to create a backup of my laptop (running Kubuntu) on my external hard drive. Due to some reasons, I had to format my laptop and do fresh install of Kubuntu. Taking backup was quite simple. How do I restore this backup?

**Comment by spersson** [comment]
I'm assuming you are using version 0.7.1 then. If so, things have improved a bit in later versions. See issue #58 .
If updating to a later version is troublesome, what you can do is to make sure bup and kup are installed, then plug in your hard drive, mount it and figure out where it is mounted. Then from a terminal run kup-filedigger with the path to your backups as the only argument. From filedigger you can restore individual files or whole folders. That older version of filedigger also can appear frozen while working on big backups. Good luck! Please post more comments if you run in to problems.
