### ISSUE TITLE
Ubuntu Vivid - Selected folders are not saved

### ISSUE THREAD

**Issue by asitemade4u** [spersson/Kup#26]
Hi,
I just installed KUP which seems very promising on my new installation of Ubuntu Vivid Vervet [15.04].
The Indicator appears well and all functions seem to work well too.
BUT the folders I select using the Configure > Source function are not backed up.
Here is a capture of the upper part of my selection:
![capture du 2015-04-28 10 33 20](https://cloud.githubusercontent.com/assets/11460106/7371976/097c82c8-ed92-11e4-86fd-4670dae3cc3f.png)

As an example, nothing in /home/stsinc/lampstack-5.4.22-0/apps/aca/htdocs/wp-content gets backed up.

Am I doing something wrong?

Thx
Stephen

**Comment by asitemade4u** [comment]
BTW here is the execution log that might help:

/* --------------------------------------------------*/
bup -d /media/sauve/Sauvegardes/Kup init
bup -d /media/sauve/Sauvegardes/Kup fsck --quick
bup -d /media/sauve/Sauvegardes/Kup index -u --exclude /home/stsinc/.gimp-2.8 --exclude /home/stsinc/Public --exclude /home/stsinc/.oh-my-zsh --exclude /home/stsinc/.compiz --exclude /home/stsinc/.dropbox --exclude /home/stsinc/.fontconfig --exclude /home/stsinc/.fonts --exclude /home/stsinc/.freemind --exclude /home/stsinc/BN - SASS --exclude /home/stsinc/.gstreamer-0.10 --exclude /home/stsinc/.openshot --exclude /home/stsinc/Modèles --exclude /home/stsinc/.nvm --exclude /home/stsinc/Documents --exclude /home/stsinc/lampstack-5.4.22-0/apps/sex/htdocs/wp-content/node_modules --exclude /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content/node_modules --exclude /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content/upgrade --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/w3tc-config --exclude /home/stsinc/.rvm --exclude /home/stsinc/.xmind --exclude /home/stsinc/.vuescan --exclude /home/stsinc/.sass-cache --exclude /home/stsinc/.quicksynergy --exclude /home/stsinc/lampstack-5.4.22-0/apps/bnm/htdocs/wp-content/upgrade --exclude /home/stsinc/.cups --exclude /home/stsinc/.gdfuse --exclude /home/stsinc/.TrueCrypt --exclude /home/stsinc/.Ephox --exclude /home/stsinc/lampstack-5.4.22-0/apps/asite4u/htdocs/wp-content/test --exclude /home/stsinc/.filezilla --exclude /home/stsinc/lampstack-5.4.22-0/apps/bnm/htdocs/wp-content/languages --exclude /home/stsinc/.multisystem --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/cache --exclude /home/stsinc/lampstack-5.4.22-0/apps/aca/htdocs/wp-content/upgrade --exclude /home/stsinc/BN - Grunt --exclude /home/stsinc/.kde --exclude /home/stsinc/.subversion --exclude /home/stsinc/.ssr --exclude /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content/reports --exclude /home/stsinc/.tor-browser-en --exclude /home/stsinc/.rpmdb --exclude /home/stsinc/.composer --exclude /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content/ewww --exclude /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content/upgrade --exclude /home/stsinc/.wp-cli --exclude /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/test --exclude /home/stsinc/.gramps --exclude /home/stsinc/.yEd --exclude /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content/node_modules --exclude /home/stsinc/.gvfs --exclude /home/stsinc/.shutter --exclude /home/stsinc/.gurlchecker --exclude /home/stsinc/.purple --exclude /home/stsinc/.gdmap --exclude /home/stsinc/.node-gyp --exclude /home/stsinc/.winff --exclude /home/stsinc/.liferea_1.8 --exclude /home/stsinc/.adobe --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/languages --exclude /home/stsinc/lampstack-5.4.22-0/apps/muffetta/htdocs/wp-content/upgrade --exclude /home/stsinc/.mysql --exclude /home/stsinc/.xbindkeys_config --exclude /home/stsinc/.gem --exclude /home/stsinc/.gnupg --exclude /home/stsinc/.google --exclude /home/stsinc/.xnconvert --exclude /home/stsinc/.gconf --exclude /home/stsinc/.rubies --exclude /home/stsinc/.bitrock --exclude /home/stsinc/.thumbnails --exclude /home/stsinc/.pulse --exclude /home/stsinc/.mono --exclude /home/stsinc/.icons --exclude /home/stsinc/BN - wpContent --exclude /home/stsinc/.ssh --exclude /home/stsinc/lampstack-5.4.22-0/apps/sex/htdocs/wp-content/test --exclude /home/stsinc/.trgtd-installer --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/_modulemanager_tmp_ --exclude /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/.sass-cache --exclude /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content/test --exclude /home/stsinc/.dbus --exclude /home/stsinc/.audacity-data --exclude /home/stsinc/.npm --exclude /home/stsinc/.qalculate --exclude /home/stsinc/.bundler --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/upgrade --exclude /home/stsinc/lampstack-5.4.22-0/apps/sex/htdocs/wp-content/upgrade --exclude /home/stsinc/.pdfsam --exclude /home/stsinc/LogicielsJava --exclude /home/stsinc/.gegl-0.0 --exclude /home/stsinc/.local --exclude /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/node_modules --exclude /home/stsinc/.gnome2_private --exclude /home/stsinc/BN - rsp --exclude /home/stsinc/.hplip --exclude /home/stsinc/.mozilla --exclude /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content/_modulemanager_tmp_ --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/test --exclude /home/stsinc/.bottles --exclude /home/stsinc/.remmina --exclude /home/stsinc/.gnome2 --exclude /home/stsinc/Bureau --exclude /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/upgrade --exclude /home/stsinc/.RationalPlan --exclude /home/stsinc/.gnome --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/upgrade --exclude /home/stsinc/.dbeaver --exclude /home/stsinc/.VirtualBox --exclude /home/stsinc/.wine --exclude /home/stsinc/lampstack-5.4.22-0/apps/asite4u/htdocs/wp-content/upgrade --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/reports --exclude /home/stsinc/.xnviewmp --exclude /home/stsinc/lampstack-5.4.22-0/apps/asite4u/htdocs/wp-content/node_modules --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/w3tc --exclude /home/stsinc/.zotero --exclude /home/stsinc/.acetoneiso --exclude /home/stsinc/.vineyard --exclude /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content/upgrade --exclude /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content/ToDos --exclude /home/stsinc/.appDrawerConfig --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/ToDos --exclude /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content/.sass-cache --exclude /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content/infinitewp --exclude /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content/test --exclude /home/stsinc/.java --exclude /home/stsinc/.putty --exclude /home/stsinc/.pyrenamer --exclude /home/stsinc/.libreoffice --exclude /home/stsinc/BN - CSS --exclude /home/stsinc/.easytag --exclude /home/stsinc/.aptitude --exclude /home/stsinc/.pybackpack --exclude /home/stsinc/.giteye --exclude /home/stsinc/.pki --exclude /home/stsinc/.Skype --exclude /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content/node_modules --exclude /home/stsinc/.dropbox-dist --exclude /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content/node_modules --exclude /home/stsinc/.mplayer --exclude /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content/_modulemanager_tmp_ --exclude /home/stsinc/.icedtea --exclude /home/stsinc/.grunt-init --exclude /home/stsinc/lampstack-5.4.22-0 --exclude /home/stsinc/.grsync --exclude /home/stsinc/.macromedia --exclude /home/stsinc/.qws --exclude /home/stsinc/.cache --exclude /home/stsinc/.nowplaying --exclude /home/stsinc/PDF --exclude /home/stsinc/.thunderbird --exclude /home/stsinc/.swt --exclude /home/stsinc --exclude /home/stsinc/.config --exclude /home/stsinc/ThoughtManager --exclude /home/stsinc/.FBReader --exclude /home/stsinc/.PlayOnLinux --exclude /home/stsinc/.secpanel --exclude /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content/_modulemanager_tmp_ /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/seed/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/aca/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content /home/stsinc /home/stsinc/lampstack-5.4.22-0/apps/bnm/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/asite4u/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/muffetta/htdocs/wp-content /home/stsinc/Documents/Scripts /home/stsinc/lampstack-5.4.22-0/apps/sex/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content
bup -d /media/sauve/Sauvegardes/Kup save -n kup /home/stsinc/lampstack-5.4.22-0/apps/ccarmody/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/seed/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/aca/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/affb/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/carmet/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/drcaren/htdocs/wp-content /home/stsinc /home/stsinc/lampstack-5.4.22-0/apps/bnm/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/vtr/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/asite4u/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/muffetta/htdocs/wp-content /home/stsinc/Documents/Scripts /home/stsinc/lampstack-5.4.22-0/apps/sex/htdocs/wp-content /home/stsinc/lampstack-5.4.22-0/apps/rou/htdocs/wp-content
bup -d /media/sauve/Sauvegardes/Kup fsck -g

Kup successfully completed the bup backup job.

**Comment by spersson** [comment]
Thanks for reporting!

First I was thinking that you encountered issue #4, but looking closer I can see that "/home/stsinc" is being both included and excluded, which is a bug I have not seen before. Can you please also post the saved configuration file, /home/stsinc/.kde4/share/config/kuprc, just to confirm that it is both included and excluded there also. My suspicion is that you have found a way of confusing the configuration dialog, with showing and hiding hidden files or something like that. I would be grateful if you could maybe create another backup plan, make a simple selection of sources and confirm that it works. After confirming that, if you can try to recreate the steps of how you made selections in the first case and see if you can find out where things go wrong. To save time you don't have to actually backup anything, just look at the configuration file and confirm that the "Paths excluded" and "Paths included" match what you expect. It should only be possible to have a path excluded which is a sub directory of an included path.
