### ISSUE TITLE
kup_0.5.1-1_amd64.deb doesn't work

### ISSUE THREAD

**Issue by omega3** [spersson/Kup#30]
I downloaded 
http://download.opensuse.org/repositories/home:/simper:/kup/xUbuntu_14.04/amd64/kup_0.5.1-1_amd64.deb
and installed
I use Kubuntu 14.04 64 bit. KDE 4.13.3 QT 4.8.6
3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

apt-cache policy kup
kup:
  Installed: 0.5.1-1
  Candidate:   0.5.1-1
  Version:
 *** 0.5.1-1 0
        100 /var/lib/dpkg/status

apt-cache policy bup
bup:
  Installed: 0.25-1
  Candidate:   0.25-1
  Version:
 *** 0.25-1 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status

but when I type kup in terminal it says that kup is not installed. To run kup ask administrator to install kup-client.

**Comment by Neudrino** [comment]
The package *kup-client* does not refer to Kub-Backup System, but to the [**k**ernel.org **up**load tool](http://packages.ubuntu.com/trusty/kup-client).
Kup-Backup is usually integrated into System Setting (see screenshot). This works fine for me for the above specified version.
![kub-integration_in_systemsteuerung](https://cloud.githubusercontent.com/assets/13189449/8513250/e8c3378c-2362-11e5-8bf7-f8afd984b738.jpg)

Nevertheless I cannot start a backup, as the 3 options in context menu of tray icon (start, show files, show log) are disabled.

Please let me know, what the expected behaviour is, or what additional information is required.

**Comment by Neudrino** [comment]
Found the problem:
The default backup destination is */home/$USER/.bup/*, but if this does not exist, a backup is not possible. The mentioned destination will not be created automatically, but you have to do it manually.
This solves above problem!

If it were not for the next to arise:
"Kup did not successfully complete the bup backup job: failed to index everything."
But I guess I should write a new bug report / question to solve it...

**Comment by omega3** [comment]
On my system it doesn't even start because system claims that there is no such program installed. Where it installs itself?

In /usr/sbin/  nothing there.
I only found:

file:///usr/bin/kup-daemon
file:///usr/bin/kup-filedigger
------------------------------------------------------------

----------------
I have installed

apt-cache policy libqt4-dev
libqt4-dev:
  Zainstalowana: 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1
  Kandydująca:   4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1
  Tabela wersji:
 *** 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4:4.8.5+git192-g085f851+dfsg-2ubuntu4 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages


apt-cache policy libkdeui5
libkdeui5:
  Zainstalowana: 4:4.13.3-0ubuntu0.2
  Kandydująca:   4:4.13.3-0ubuntu0.2
  Tabela wersji:
 *** 4:4.13.3-0ubuntu0.2 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4:4.13.0-0ubuntu1 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages



apt-cache policy libkfile4
libkfile4:
  Zainstalowana: 4:4.13.3-0ubuntu0.2
  Kandydująca:   4:4.13.3-0ubuntu0.2
  Tabela wersji:
 *** 4:4.13.3-0ubuntu0.2 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4:4.13.0-0ubuntu1 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages


apt-cache policy libsolid4
libsolid4:
  Zainstalowana: 4:4.13.3-0ubuntu0.2
  Kandydująca:   4:4.13.3-0ubuntu0.2
  Tabela wersji:
 *** 4:4.13.3-0ubuntu0.2 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4:4.13.0-0ubuntu1 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages



apt-cache policy openssl
openssl:
  Zainstalowana: 1.0.1f-1ubuntu2.15
  Kandydująca:   1.0.1f-1ubuntu2.15
  Tabela wersji:
 *** 1.0.1f-1ubuntu2.15 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://pl.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
------------------------------------------

I also tried to compile but error occured: 

cmake ..
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
http-parser was not found or is too old; using bundled 3rd-party sources.
zlib was not found; using bundled 3rd-party sources.
CMake Error at /usr/share/cmake-2.8/Modules/FindKDE4.cmake:98 (message):
  ERROR: cmake/modules/FindKDE4Internal.cmake not found in
  /home/yellow/.kde/share/apps;/usr/share/kubuntu-default-settings/kde4-profile/default/share/apps;/usr/share/kde4/apps
Call Stack (most recent call first):
  CMakeLists.txt:6 (find_package)


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/yellow/Pobrane/Kup-kup-0.5.1/build/CMakeFiles/CMakeOutput.log".
---------------------------------
CMakeOutput.log
http://pastebin.com/g6cz67z3

**Comment by Neudrino** [comment]
Hey @omega3,
maybe I mention again, that I am not a developer, but just an average Kubuntu user, so that I might not be able to go into detail...
Anyway, there is no separate executable in */usr/bin/* for the backup program. The two binaries you mentioned are enough. As said above, use your system settings to access it! It is marked blue / selected on the above screenshot. Maybe check whether an autostart entry is present. Enclosed you may find all installed files on my installation.

```
/usr/bin/kup-daemon
/usr/bin/kup-filedigger
/usr/share/autostart/kup-daemon.desktop
/usr/share/doc/kup/changelog.Debian.gz
/usr/share/icons/hicolor/32x32/actions/kuprunning.mng
/usr/share/icons/hicolor/scalable/apps/kup.svgz
/usr/share/kde4/apps/kup-daemon/kup-daemon.notifyrc
/usr/share/kde4/services/bup.protocol
/usr/share/kde4/services/kcm_kup.desktop
/usr/share/locale/de/LC_MESSAGES/kup.mo
/usr/share/locale/es/LC_MESSAGES/kup.mo
/usr/share/locale/fr_FR/LC_MESSAGES/kup.mo
/usr/share/locale/it/LC_MESSAGES/kup.mo
/usr/share/locale/lt_LT/LC_MESSAGES/kup.mo
/usr/share/locale/pl/LC_MESSAGES/kup.mo
/usr/share/locale/pt_BR/LC_MESSAGES/kup.mo
/usr/share/locale/ru/LC_MESSAGES/kup.mo
/usr/share/locale/sv/LC_MESSAGES/kup.mo
/usr/share/locale/tl/LC_MESSAGES/kup.mo
/usr/share/locale/zh_TW/LC_MESSAGES/kup.mo
```

I did not try to compile, as the .deb-Package works fine for me.

**Comment by omega3** [comment]
Ok. Now I got it. Thank you very much.
