### ISSUE TITLE
[question] open files directly from an archive

### ISSUE THREAD

**Issue by omega3** [spersson/Kup#33]
Can you explain this to me, please: 
"Kioslave for accessing bup archives. This allows you to open files and folders directly from an archive, with any KDE application."
Does it mean that I could see backed up files in Dolphin?

I did backup but the only files I can see in destination folder are:
http://i.imgur.com/MVR4goO.png

Where is the actual backup file stored? Maybe this is silly question but I expected to see the same catalogue tree as in /home or at least any compressed file like tar.gz or whatever.

**Comment by spersson** [comment]
The actual file contents of your backup is in the "objects" folder that you can see there. But you can't access it directly like that. I have tried to mention this in the configuration, when you create a new backup plan.. Under "backup type" it explains a bit more about versioned backups.
So anyway... the easy way to look at your backups is to click on the system tray icon, in the popup menu, under your backup plan you can choose "Show files". That will show you your backups, sorted not by date but by contents. From there you can choose and folder and click the "open" button.. that will open the folder in your file manager. (this is where the Kioslave is used, notice the "bup://" protocol). From there you can navigate around, going up some levels you can see that it is all sorted by date here. You can look at files but not change them. If you want to restore a file you can copy it directly from Dolphin but the recommended way is to use the "Restore" button in that first window that opened.
Hope this helps!
