### ISSUE TITLE
Kup did not successfully complete the bup backup job: failed to index everything.

### ISSUE THREAD

**Issue by Neudrino** [spersson/Kup#34]
The Problem is, that Kup fails to do the backup with the message:
``` Kup did not successfully complete the bup backup job: failed to index everything. ```

The backup works fine for most folders, but if I include some specific ones, it is always failing.
If I do run bup on command line on the "bad folders" I do neither get an error nor an positive answer that everything worked. But as far as I can guess, the backup destination stays empty.

**Comment by Neudrino** [comment]
I think I found a problem:
It is somehow difficult to describe, but it is maybe somehow about user right and somehow not at the same time.

It seems that Kup / bup does not go well with bind mounted Folders.

**The system environment:**
I have my a SSD and a HDD in my machine. The SSD hosts the system and /home folder. The bigger data is on the HDD. I integrated the HDD folders by fstab mounts to the users home folder.
e.g. I added in fstab
``` /media/Medien/.user/neudrino/Archive     /home/neudrino/Archive   none    bind    0       0 ```
which results in the ```ls -l ~``` output
```drwxrwxrwx  1 root     root      4096 Jul 11 15:00 Archive/```
whereas normal folders show up as
```drwxrwxrwx  1 neudrino neudrino      4096 Jul 11 15:00 Pictures/```.
The *Archive* folder has several sub folders, which are also owned by *root*. E.g. the folder structure looks like
```
Archives
   |- 2014 folder
   |- 2013 folder
```

Now **the problem** is, that bup does fail to index the *Archive* folder.
If I include the *Archive* folder in the backup, the whole index process will fail. But (and that is puzzling me) if I exclude the *Archive* folder but include the *2014 folder* and *2013 folder* the backup works just fine!
So the directory permissions cannot cause the issue, as both, the *Archive* folder and its subfolders, are owned by *root*.

I thought about replacing the bind mounts with some symlinks, but bup will not follow these, so that it is no option.

Any ideas?

**Comment by spersson** [comment]
On July 11, 2015 06:27:08 Neudrino wrote:
> I think I found a problem:
> It is somehow difficult to describe, but it is maybe somehow about user
> right and somehow not at the same time.
> 
> It seems that Kup / bup does not go well with bind mounted Folders.
> 
> **The system environment:**
> I have my a SSD and a HDD in my machine. The SSD hosts the system and /home
> folder. The bigger data is on the HDD. I integrated the HDD folders by
> fstab mounts to the users home folder. e.g. I added in fstab
> ``` /media/Medien/.user/neudrino/Archive     /home/neudrino/Archive   none  
>  bind    0       0 ``` which results in the ```ls -l ~``` output
> ```drwxrwxrwx  1 root     root      4096 Jul 11 15:00 Archive/```
> whereas normal folders show up as
> ```drwxrwxrwx  1 neudrino neudrino      4096 Jul 11 15:00 Pictures/```.
> The *Archive* folder has several sub folders, which are also owned by
> *root*. E.g. the folder structure looks like ```
> Archives
> 
>    |- 2014 folder
>    |- 2013 folder
> 
> ```
> 
> Now **the problem** is, that bup does fail to index the *Archive* folder.
> If I include the *Archive* folder in the backup, the whole index process
> will fail. But (and that is puzzling me) if I exclude the *Archive* folder
> but include the *2014 folder* and *2013 folder* the backup works just fine!
> So the directory permissions cannot cause the issue, as both, the *Archive*
> folder and its subfolders, are owned by *root*.
> 
> I thought about replacing the bind mounts with some symlinks, but bup will
> not follow these, so that it is no option.
> 
> Any ideas?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spersson/Kup/issues/34#issuecomment-120617498

I would have expected you to get some more detailed error message from bup, in the log 
file... that would have been helpful.

My first suspect would be a hidden file or folder in the Archive folder, something which you 
do not have read access to, only root can read perhaps.
At least then it would make sense. Kup will not record the backup as being successful 
unless everything got backed up correctly. Of course it can seem a bit silly that a 1 KB text 
file you don't care about could cause a failure for a 300 GB, otherwise successful, backup. 
But I don't think it is right to do anything else.. I don't have any good idea for how to say 
"ehh.. so that file didn't get backed up... what the hell, user probably doesn't need that file 
anyway, let's just tell the user that everything is ok" and get away with it... :)

Thanks for reporting anyway! Let me know what you find...

**Comment by Neudrino** [comment]
> I would have expected you to get some more detailed error message from bup, in the log file... that would have been helpful.

Sorry, that I was not able to give more information.
If you referring to Kup log file, there is no more information printed there. It just prints out the above line directly after the *bup index* command. :-/
I am not aware that bup itself writes a log file? If so, let me know where to get it from.

> My first suspect would be a hidden file or folder in the Archive folder, something which you do not have read access to, only root can read perhaps.

I checked this, but permission were set with ```chmod 777 ./*``` so that all files in the folder in question are perfectly readable by the user account. I have also no trouble viewing any file from dolphin.

---

I have constructed an "minimal example" to **reproduce the bug**:
* Kubuntu 14.04, kup_0.5.1-1_amd64.deb installed
* prerequisites: 2 partitions, one of which is the "home-partition", the other one is "theOtherPartition"

Steps to reproduce:
* make several folders for testing purpose
```bash
mkdir /media/$theOtherPartition/mountFolder
mkdir /media/$theOtherPartition/mountFolder/subFolder1
mkdir /media/$theOtherPartition/mountFolder/subFolder2
echo "test" >> /media/$theOtherPartition/mountFolder/subFolder2/test.txt
mkdir /home/$USER/mountPoint
```
* mount the folders to new location
```bash
sudo mount --bind /media/$theOtherPartition/mountFolder /home/$USER/mountPoint
sudo chmod 777 ~/mountPoint/* # just to make sure, but usually not required, as permissions are already OK
```
* setup new backup which backs up solely *mountPoint* to some destination
* check upon following configurations:
 * backup whole *mountPoint*
 * backup *subFolder1* only
 * backup *subFolder2* only

**Results** on my machine:
* backup whole *mountPoint* : fails
* backup *subFolder1* only : works
* backup *subFolder2* only : fails

--

Hope you can reproduce the bug and see that there is not more debug information in Kup log-file.

----------

> Kup will not record the backup as being successful unless everything got backed up correctly. Of course it can seem a bit silly that a 1 KB text file you don't care about could cause a failure for a 300 GB, otherwise successful, backup. But I don't think it is right to do anything else.. I don't have any good idea for how to say "ehh.. so that file didn't get backed up... what the hell, user probably doesn't need that file anyway, let's just tell the user that everything is ok" and get away with it... :)

I fully understand your point, why it is going to say "backup incomplete" as soon as there is 1KB missing. I totally agree with this policy!

**Comment by spersson** [comment]
I tried reproducing this by following the steps you mention, using bup 0.27. The only problem I found was an issue in bup that I have reported on the bup mailing list today (https://groups.google.com/forum/#!topic/bup-list/sceZbQoLBLU), but it turned out to not have anything to do with bind mounts. And the error output did show up in the kup log file.
I will close this issue as it most likely has to do with bup, not kup. If you do think that kup is doing something wrong then please reopen and we'll try to figure it out!
