### ISSUE TITLE
Allow for deselecting the user home directory

### ISSUE THREAD

**Issue by Neudrino** [spersson/Kup#35]
In normal mode, the users home directory will be backed up with all hidden folders (and all non hidden ones). If one only selectively wants to backup some folder to a special device, it would be cool, if one could deselect the home folder as to prevent backup of all other (hidden) folders.
Often there is no need to backup the hidden configuration files and it is cumbersome to deselect all hidden stuff one by one.

**Comment by spersson** [comment]
On July 11, 2015 06:40:05 Neudrino wrote:
> In normal mode, the users home directory will be backed up with all hidden
> folders (and all non hidden ones). If one only selectively wants to backup
> some folder to a special device, it would be cool, if one could deselect
> the home folder as to prevent backup of all other (hidden) folders. Often
> there is no need to backup the hidden configuration files and it is
> cumbersome to deselect all hidden stuff one by one.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spersson/Kup/issues/35

What is stopping you from deselecting a folder? What you are describing is most 
definitely possible, just click the checkbox next to the name of the folder.
Just note that deselecting the home folder and then only selecting some 
folders under the home folder will not only exclude the hidden folders but also 
any file placed directly in the home folder.

**Comment by Neudrino** [comment]
Thanks for your quick reply!

> What is stopping you from deselecting a folder? What you are describing is most definitely possible, just click the checkbox next to the name of the folder.

The funny thing is, that of course I tried exactly what you suggest. Just clicking the checkbox next to home folder. But for me this checkbox is not functional. The checkbox is semi-checked (with dashed tick) when creating a new backup plan. I can click the checkbox as often as I want, but it is not changing its status. Neither to fully checked, nor to unchecked.

If I enable hidden folders and uncheck all folders inside home, it is not becoming unchecked either. This is probably normal behaviour, as there are many (hidden) files in home directory.

> Just note that deselecting the home folder and then only selecting some folders under the home folder will not only exclude the hidden folders but also any file placed directly in the home folder.

Yes I am aware of this and this is the expected behaviour for me. Thanks that you pointed it out again.

I would do you a video of this, but never did such a thing before, so this would probably take me ages.
-
Kubuntu 14.04, kup_0.5.1-1_amd64.deb installed

**Comment by Neudrino** [comment]
For your convenience... :smirk: :smile: 
https://copy.com/HoGMjW6iosYutCvP

**Comment by spersson** [comment]
Just a small (very late) reply to this.... I did see your video but I just didn't have any clue what could cause it to not work for you. Sorry, I should have replied then but have just been busy... that's all. It would be interesting to hear if anybody else is seing this problem. Or if anybody has the same problem with Kup 0.6.0 (based on Qt 5 and KF5)...

**Comment by Silicomancer** [comment]
I experienced that too. Kubuntu 15.10. The checkbox is semi-checked for new backup plans. I could deselect all subfolders (even hidden ones) still this is nasty. It would be better to not check any folders by default when creating a new backup.

Anyway I really like Kup! The interface and integration is wonderful. Please keep it alive!

**Comment by spersson** [comment]
@Silicomancer : Please confirm that you mean that the checkbox next to the home folder would not change (ticked/unticked) when you click on it. This issue report has nothing to do with if it the default backup plan is good or not.
I'm just wishing I had some time to look into these issues some more... :(

**Comment by Silicomancer** [comment]
Yes, confirmed. I can untick the checkboxes of all sub-folder in home (one by one, what a pain) but NOT the checkbox of the home folder itself.

The sentence about the default backup plan was a related remark only.

**Comment by Neudrino** [comment]
I have just been able to check with newer packages and distros.

Today, I checked with
:+1: **Manjaro Linux + Kup 0.6.1** (from Repo): works.
:+1: **Kubuntu 16.04 + Kup 0.6.0** (deb from https://launchpad.net/~martin-loschwitz/+archive/ubuntu/kup): works.

Moreover I discovered a **workaround** for **Kubuntu 14.04 + Kup 0.5.1**:
While I could not change the state of my home-folder "/home/$USER", I was able to change the state of the folder "/home". Thus selecting and deselecting the "/home/"-folder will also deselect the personal home-folder. When the the home-folder has changed state once, it is changeable afterwards as normal.

I did just check upon this one special issue, and not complete use case, as I was just testing the new LTS today, but had no time to migrate the system from Precise to Xenial yet.

**Comment by spersson** [comment]
thanks @Neudrino for the update. I will just close this issue now then.
