### ISSUE TITLE
Can't open files after a backup

### ISSUE THREAD

**Issue by sbaragnaus2** [spersson/Kup#43]
Hi,
I've just made an incremental backup. If I open a file form backup using the icon in the taskbar (bottom right) I have an error.

This happens with pictures (gwenview) and pdf (okular). Instead I can open zip (Ark) and documents (Libreoffice). I'm running Manjaro Linux with kde. Kernel: 4.7.5 

Here is gwenview backtrace: http://pastebin.com/Rq3mAb4g

Here is Okular error message: 

```
can't open bup:/run/media/sbaragnaus2/Verbatimhdd/Backup-kup//kup/2016-10-08 19:43/home/sbaragnaus2/Pictures/readme.pdf. Cause: Could not start process 
Unable to create io-slave:
klauncher said: «bup» protocol is unknown.

```

Please note: bup is installed in my system and kup is 0.6.1

**Comment by spersson** [comment]
On Sunday, 9 October 2016 01:33:15 SGT sbaragnaus2 wrote:
> Hi,
> I've just made an incremental backup. If I open a file form backup using the
> icon in the taskbar (bottom right) I have an error.
> 
> This happens with pictures (gwenview) and pdf (okular). Instead I can open
> zip (Ark) and documents (Libreoffice). I'm running Manjaro Linux with kde.
> Kernel: 4.7.5
> 
> Here is gwenview backtrace: http://pastebin.com/Rq3mAb4g
> 
> Here is Okular error message:
> ```
> can't open bup:/run/media/sbaragnaus2/Verbatimhdd/Backup-kup//kup/2016-10-08
> 19:43/home/sbaragnaus2/Pictures/readme.pdf. Cause: Could not start process
> Unable to create io-slave:
> klauncher said: �bup� protocol is unknown.
> 
> ```
> 
> Please note: bup is installed in my system

I suspect it's an installation issue. This is from my system:

~ $ locate bup.protocol 
/usr/share/kservices5/bup.protocol 
~ $ locate kio_bup 
/usr/lib/qt/plugins/kio_bup.so

Please locate those files on your system and also check in those folders if 
that is where all the other kioslave plugins on your system are installed.

**Comment by montefra** [comment]
I have (probably) same problem on OpenSUSE leap 42.1.
I get an error if I try to open:
* directory
* pdf (okular)
* mp3: Amarok says file ``bup:///run/...`` not found
* text file in vim

Kind of work:
* tar.gz, zip: opens ark but doesn't load the archive
* jpg, png: opens gwenview but doesn't show the file

This are my settings:
-> locate bup.protocol
/usr/share/kservices5/bup.protocol
-> locate kio_bup
/usr/lib64/qt5/plugins/kio_bup.so
> ls /usr/lib64/qt5/plugins/kio_*
/usr/lib64/qt5/plugins/kio_about.so         /usr/lib64/qt5/plugins/kio_bluetooth.so  /usr/lib64/qt5/plugins/kio_kamera.so
/usr/lib64/qt5/plugins/kio_activities.so    /usr/lib64/qt5/plugins/kio_bup.so        /usr/lib64/qt5/plugins/kio_obexftp.so
/usr/lib64/qt5/plugins/kio_applications.so  /usr/lib64/qt5/plugins/kio_fonts.so      /usr/lib64/qt5/plugins/kio_remote.so

Let me know if you need more info.

**Comment by spersson** [comment]
Hmmm... 
Did you confirm that other *.protocol files are stored under /usr/share/kservices5/ also?
Sorry if that's not very helpful, I just keep thinking that this issue is simply that KDE libraries are not finding the added bup protocol. And asking you is so much easier for me than trying to find out where different distros store files...
Thank you for the info anyway! And sorry that I'm not more helpful, I simply don't know what else could be the problem...

**Comment by spersson** [comment]
Closing this now, still seems like some packaging issue. Anybody who still experience this issue, feel free to reopen.
