### ISSUE TITLE
Extend program description with more detailed install instructions

### ISSUE THREAD

**Issue by Neudrino** [spersson/Kup#45]
I think, more detailed install instruction in Readme.md and on linux-apps.com would be helpfull for users. Of course, downloading the appropriate file from your opensuse repo is not difficult for advanced users. However, new users might be lost.
For xUbuntu users adding a repo is usually the easiest way. This should be explained in more detail.
(I am a Kubuntu user for a while now, and it took me more than 10 min to sort out all "problems".)

I am on Kubuntu 16.04, so I give a example, what I think might be a good idea to include:

> Installing **kup** in (K)Ubuntu 16.04 LTS is possible with the following commands given to a terminal:
> ```bash
> sudo add-apt-repository 'deb http://download.opensuse.org/repositories/home:/simper:/kup/xUbuntu_16.04/ /'
> wget http://download.opensuse.org/repositories/home:/simper:/kup/xUbuntu_16.04/Release.key && sudo apt-key add Release.key && rm Release.key
> sudo apt update && sudo apt install kup
> ```

You might want to include a description, which is not xenial specific (did not test, but should work):

> Installing **kup** is possible with the following commands given to a terminal line by line.
> Please have a look at http://download.opensuse.org/repositories/home:/simper:/kup/ for available version. Add the version-string without trailing slash where indicated.
> ```bash
> YOUR_VERSION="Your version string goes here!"
> sudo add-apt-repository 'deb http://download.opensuse.org/repositories/home:/simper:/kup/$YOUR_VERSION/ /'
> wget http://download.opensuse.org/repositories/home:/simper:/kup/$YOUR_VERSION/Release.key && sudo apt-key add Release.key && rm Release.key
> sudo apt update && sudo apt install kup
> ```

Comment: Piping wget to apt did not work for me. Therefore the cumberstone workaround.

Thank you for the great programm!

**Comment by spersson** [comment]
Thanks for your suggestions!
Can I first just ask some questions... It's been many years now since I changed away from kubuntu. If the user just downloads the deb with web browser from the opensuse build repo... then double click on the downloaded file, what happens? (with a default install..)
Is it as nice as I imagine it... that it asks for authorization to modify the system, then shows what would be installed, you can click install and dependencies are installed and the local deb is installed?
I was just assuming that as long as the dependencies of kup are in universe repo that it can be done very easily like that.
Of course the way you suggest would have the significant advantage of notifying the user whenever I publish a new version of kup.
Btw, work is ongoing to get a kup package included in debian.

**Comment by thomaspierson** [comment]
FYI I'm working on packaging Kup into Debian official archive. Once the package is accepted into unstable repository, it will normally migrate into all debian derivative distros like kubuntu. Stay tuned! :)

**Comment by darkbluelight** [comment]
> FYI I'm working on packaging Kup into Debian official archive.

@thomaspierson OMG you are my hero! IMO bup with the kup GUI is the best FOSS backup software available. It's the first FOSS solution that comes close to the GUI and functionality of the proprietary crashplan.com which I was using before as my favorite solution, but wanted to get rid of.

I don't understand why kup doesn't get more attention (especially in the Cinnamon desktop community) and why kup isn't available on Debian officialy. bup in the command line / terminal is a pain to use and bups, the GTK GUI, is unfortunately far from finished and useful.

@spersson you are a hero anyway for creating kup.

you two: paste / send me your Bitcoin or Dash addresses and I'll donate you a thank you.

**Comment by darkbluelight** [comment]
BTW the release key of http://download.opensuse.org/repositories/home:/simper:/kup/Debian_8.0/ has expired, are you aware of that?

Synaptic on Debian gives an error while trying to update the kup package and aborts. One can install kup only through apt-get in the terminal, which gives an error warning as well, but allows to proceed with the package update and the install afterwards)

**Comment by spersson** [comment]
Closing this issue, thanks again for suggestions!
Kup is now included in both debian testing and ubuntu 18.04.
