### ISSUE TITLE
Appdata file validation fails

### ISSUE THREAD

**Issue by mattiaverga** [spersson/Kup#49]
I'm trying to package Kup for inclusion in Fedora, but the appdata file fails validation check:
? tag-invalid           : stock icon is not valid [kup] 

Removing "type=stock" make the validation pass, but since the appdata file is automatically generated at buildtime I don't know how to make this.

**Comment by spersson** [comment]
That is very exciting news! Thank you!
I am not familiar with appdata files, and my knowledge of spec files is very very limited. I would be very willing to help figure it out but I don't have time for at least a couple of weeks. Perhaps @thomaspierson can help? He recently got kup into [debian](https://packages.debian.org/unstable/kup-backup)! Woohoo!

**Comment by spersson** [comment]
On 2017-04-30 15:16, Mattia Verga wrote:

> I'm trying to package Kup for inclusion in Fedora, but the appdata file fails validation check:
> ? tag-invalid : stock icon is not valid [kup] 
> 
> Removing "type=stock" make the validation pass, but since the appdata file is automatically generated at buildtime I don't know how to make this. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

Ok, had a quick look... So you are saying that the appdata file is
autogenerated at build time. But ideally I should be shipping it with
the rest of the sources, right? So for the next release of kup I can
perhaps include one. You could send me the one that gets generated so I
can use that as a starting point. Then I should try to get it translated
also.... 

For now, if you want to have a fedora package for version 0.6.1 you
should be able to include the manually modified version of the appdata
file alongside the spec file, right? Same like you would do with
disto-specific patches and such. 

  

Links:
------
[1] https://github.com/spersson/Kup/issues/49
[2]

**Comment by mattiaverga** [comment]
This is the autogenerated appdata file. The only problem is the "type="stock"" option of the icon element. for the moment I can easily fix inside the spec file.

I can't build 0.6.1 because I need to make Kup use system libgit, so I just went ahead and I'm building the master tree. 

Thank you.

[org.kde.kupapplet.appdata.zip](https://github.com/spersson/Kup/files/975366/org.kde.kupapplet.appdata.zip)

**Comment by thomaspierson** [comment]
@mattiaverga : I think you talk about this file `build/org.kde.kupapplet.appdata.xml` which is generated at build time.
Maybe I'm wrong but I think this is not the appdata file you think because it is just a file related to a kup plasma «applet» recently added on the master branch.
In fact I think this file is only used by the plasma applet manager which have probably its own appdata format and not for the global kup software like an usual appstream file.

@spersson : I will try to produce a real appstream file as soon as I get some time.

**Comment by spersson** [comment]
@thomaspierson : very interesting info, thank you! Then looking at how other plasma packages handle it could be useful.

**Comment by spersson** [comment]
@mattiaverga : I managed to trick build.opensuse.org into building fedora packages for the newly released version 0.7.0. That maybe doesn't mean much if these build servers are not as strict as fedora projects'. The ugly spec file is here: https://build.opensuse.org/package/view_file/home:simper:kup/kup-kf5/kup.spec?expand=1

**Comment by spersson** [comment]
Closing this issue, will see about adding appstream file. Anyway, that would be a separate issue.
