### ISSUE TITLE
Creating recovery info fails with par2cmdline

### ISSUE THREAD

**Issue by dmolineus** [spersson/Kup#50]
Since par2 has changed there basepath handling, creating the recovery info fails:
https://github.com/Parchive/par2cmdline/releases/tag/v0.7.0

Would be great if kup would work with the latest release of par2 as well.

**Comment by spersson** [comment]
Kup never calls par2 directly, instead it calls bup which in turn uses par2. So if any changes are needed it would have to be done in bup.

I checked it now and somebody already reported the problem: [bup-list](https://groups.google.com/forum/#!topic/bup-list/UYZKWj-AbNU)

Thanks for reporting! Very nice.

**Comment by dmolineus** [comment]
Thanks for checking the bup-list. 

I don't know the details how bup/kip works so I opened the issue here as it was the only big tracker I found.

-----Original Message-----
