### ISSUE TITLE
Preserve folder structure when the parent is excluded

### ISSUE THREAD

**Issue by diegogangl** [spersson/Kup#55]
Imagine the following folder structure:

```
- [ ] A
-- [X] B
-- [X] C
```

When `A` is not selected but `B` and `C` are, those two folders end up at the root of the backup folder instead of inside an `A` folder (like `A/B/` and `A/C/`). It would be better if kup would create a folder for the parent and place them there. Don't know if rsync/bup have an option to do this though.

**Comment by spersson** [comment]
It behaves like this following the discussion in issue #29. People wanting to use rsync backups not only for disaster recovery but also more normal day to day usage. Why would you like A folder created? Would it not be confusing that files in folder A are not saved? When you select backup destination you can name folder A there and it will be created.

**Comment by diegogangl** [comment]
Sorry, I didn't express myself clearly. Here's a real world example: I'm not backing up everything in my video and music folders to save space, but I'm still backing quite a few (~100) folders. Kup puts all these in my backup directory mixing video, music and the parent folders I actually have in my home.
If I ever have to restore my backups without kup/rsync or find something there I'll have to work folder-by-folder. 

For instance this would be my home:
```
- music
-- album_1
-- album_2
- video
-- videos_1
-- videos_2
-work
```
Kup would save them like this: (I've set "Backup" as the destination folder)

```
- Backup
-- album_1
-- album_2
-- videos_1
-- videos_2
-- work
```

Is there a specific reason why kup tries to avoid nested folders?  I looked at the commit at the end of that issue, but couldn't figure out.
It's only a minor inconvenience though. I did my first backup today and Kup is stellar! I wish it came bundled in Neon, I would've started using it earlier :)

**Comment by spersson** [comment]
Thank you for the feedback and for the kind words! I understand your scenario better now, but I am still sceptical about how common it would be for someone to not want to include the whole of music and videos, and mark excluded sub folders instead. The important difference is what happens to sub folders added after your backup plan has been created. In your scenario such sub folders would not be saved. So anytime you add content to music folder you also need to remember to edit your backup plan, assuming you want to save the new stuff also. My assumption when creating kup was that users would not want to spend much time setting up a backup plan. Just include most things in your home folder, exclude stuff that is not necessary and then save the plan. Anyway, I will leave the issue open for more discussion and thinking.

**Comment by spersson** [comment]
Oh, regarding your question. Kup now tries to avoid it because people use rsync backup drive in daily routines, making it annoying to navigate in to your content for a series of parent folders. That was the discussion in issue #29. Previously I had cared about avoiding naming conflicts by always including all folders up to root.

**Comment by diegogangl** [comment]
Yeah I agree it's kind of a strange case. I don't mind including folders because it won't change too much, only the stuff I can't re-download.

**Comment by spersson** [comment]
I think this case is in direct conflict with issue #29. I don't see any way to satisfy both types of usage scenarios. Closing this issue since I think the other usage scenario is more common and important (convenience for daily usage beats conveniece at the time of disaster recovery).
Thank you for providing feedback on how Kup could be better for you!
