### ISSUE TITLE
No status in notification panel in plasma 5.14.4. Only buttons.

### ISSUE THREAD

**Issue by Tichy** [spersson/Kup#65]
![kup](https://user-images.githubusercontent.com/2348771/50540394-4195a380-0b91-11e9-8ab6-0dc2b61ae888.png)

I had this issue after some recent plasma update. I don't know if it was plasma or frameworks.
Anyway, my versions:

plasma 5.14.4
kde frameworks 5.53.0
qt 5.12.0

**Comment by spersson** [comment]
Fixed. Thank you!

**Comment by atomGit** [comment]
0.7.2-1 on manjaro 18 - this issue still exists
