### ISSUE TITLE
missing labels: backup status, plasma pop-up

### ISSUE THREAD

**Issue by atomGit** [spersson/Kup#66]
there are no text labels for any of the configured backup jobs in the pop-up UI when clicking the sys-tray icon - the buttons (save new, show files, show log) are there and the spaces where the labels should be are there

the labels are present on the configuration UI

wasn't able to capture a screen-shot because pressing any key causes the pop-up to hide

this is mildly interesting because it tells me there is a difference between upgrading and installing Manjaro fresh - everything was fine before a fresh install (and i cleaned out /home so there were was no .kde, .config .cache, etc. settings left)

theme color doesn't matter - i tried breeze, breeze dark, etc.

Manjaro 18.0.2 (fairly fresh) 
Plasma 5.14.4
KDE 5.53.0
Kernel 4.14.91-1-MANJARO
64-bit

**Comment by stefano-b** [comment]
Same problem here, I'm using a fully updated openSUSE Tumbleweed.

Here is a screen (sorry for the italian language, if needed I can provide another in english):

https://i.imgur.com/nJplr14.png

**Comment by spersson** [comment]
Version 0.7.3 released, contains fix. Please test and report if still any problem. Thanks!

**Comment by stefano-b** [comment]
I'm not using kup so often right now, but I can confirm that this issue is now fixed and the text labels are working as expected.
