### ISSUE TITLE
rsync: add --exclude-from file option.

### ISSUE THREAD

**Issue by linuunix** [spersson/Kup#67]
I am a plain rsync user and over the years I was "maintaining" a ignore file for rsync containing a list of files that are not important for me.     
I think it would be ideal for kup  and its users to just hand over the file to rsync instead of hunting down the folders/files to exclude in the configuration module. Kup doesn't support currently selecting files to exclude, only folders. There are plenty of dotfiles I don't care about and want to be excluded. (things like .Xauthorithy, .xsession-errors, log files ...)    
The first backup made by kup failed because there was a file in my Documents folder that can't be read by my user (intentionally) and kup suggests to ignore the whole Documents folder . 

kup 0.7.2

**Comment by spersson** [comment]
Thanks for the suggestion!
I am glad to hear you agree that selecting/deselecting individual files in the backup configuration would not be a good idea. I think it would be a bit messy to show a long list files there, when I expect most users to not care about individual files.
The expected scenario is that the user simply chooses the entire home folder, possibly with some subfolders excluded for things that are not critical.
In the interest of keeping kup simple but still flexible and powerful enough... (it's a tricky balance sometimes) can I ask you if you could move files you don't want saved in a backup to a separate folder? Seems like an easy solution :). I know that the dot files you mention are not easily moved. But they are also not very big compared to a normal sized home folder. I would not worry about a few unneccesary MB of data in a GB-sized backup.
I will consider adding an option to the "advanced" settings for rsync backups where you could simply give the file path of an exclude list. That is a simple change and gives full flexibility for excluding stuff, not only specific files but also all files names matching a pattern. That last thing is actually more of a motivation, but so far noone has asked for it!

**Comment by linuunix** [comment]
Well I could move things to a separate (sub)folder but should move them (at least some) back as they are supposed to be there where they are. It's also not fun as I have currently 69 lines of files/folders/patterns to exclude. I don't think that would be ideal to move things back and forth, "we" are lazy and try to automate stuff as much as possible :)

**Comment by spersson** [comment]
I have added this in https://invent.kde.org/kde/kup/-/commit/293a7eb607801e5cc777730e6b79176b8404d282
![image](https://user-images.githubusercontent.com/1425156/77820089-b3ed8e80-711a-11ea-8694-dc8bca766f3c.png)
