### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by stefano-b** [spersson/Kup#68]
I'm unable to take backups, here is the error log:

```
Kup is starting bup backup job at sabato 16 febbraio 2019 10:28:40 CET

bup "-d" "/run/media/stefano/DATA/backup/sbweb-LAMP" "init"
bup "-d" "/run/media/stefano/DATA/backup/sbweb-LAMP" "fsck" "--quick"
bup "-d" "/run/media/stefano/DATA/backup/sbweb-LAMP" "index" "-u" "/home/sbweb/Apps/LAMP"
Warning: python-xattr module is too old; install python-pyxattr instead.
bup "-d" "/run/media/stefano/DATA/backup/sbweb-LAMP" "save" "-n" "kup" "-vv" "/home/sbweb/Apps/LAMP"
Warning: python-xattr module is too old; install python-pyxattr instead.
Traceback (most recent call last):
  File "/usr/lib/bup/cmd/bup-save", line 377, in <module>
    meta.hardlink_target = find_hardlink_target(hlink_db, ent)
AttributeError: 'NoneType' object has no attribute 'hardlink_target'

Kup did not successfully complete the bup backup job: failed to save everything.
```

It seems to be a problem of pyhton dependencies.

If it matters, I'm on a fully updated openSUSE Tumbleweed.

**Comment by spersson** [comment]
My google skills are not good enough to solve this one. I found out now that you can install opensuse package from https://build.opensuse.org/package/show/home:ecsos:Backup/kup-kf5 which is probably better than the opensuse packages I provide. I hate packaging. But anyway, that more proper package recommends a package simply called "bup", but I am unable to find out what bup package will be installed on opensuse. I found https://software.opensuse.org/ but searching there it seems like there is no package for bup on opensuse? If you can find the bup package for opensuse that you have installed you can probably file a bug against it there.

**Comment by stefano-b** [comment]
Thank you for your reply, I've actually installed Kup from the package that you reported; I'll try to contact the packager and see if he can solve the issue.
