### ISSUE TITLE
Problems when snap packages are installed

### ISSUE THREAD

**Issue by asmerovski** [spersson/Kup#70]
When several snap applications are installed there are too many questions about symlinks to /snap folder where snap apps go. Can we have an option to include all (Apply to all) instead of answering question for every file? That is a pretty long process if there are more than 5 snaps installed.

**Comment by spersson** [comment]
Oh, I see. Yeah sounds like your suggestion could be the best solution. I would welcome a fix for this if someone wants to help out. It will be at least a month before I can work on adding it myself.

**Comment by Pointedstick** [comment]
This UI currently exposes the technical details of how Snap works in way that's sort of sub-optimal. It would be better if it automatically did the right thing in this case rather than asking the user in the first place.

**Comment by spersson** [comment]
Resolved by not warning the user in this scenario.
