### ISSUE TITLE
Poor user experience when a file in the backup set is a symlink pointing to a system file

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#72]
I have `ssh-add` as an autostart script, added with System Settings > Startup and Shutdown > Autostart. The System Settings UI expresses this as a symlink in `~/.config/autostart-scripts` to the real executable in `/usr/bin/`, and Kup handles this situation poorly. First I am presented with the following message:

![Bad message 1](https://user-images.githubusercontent.com/1097249/58387043-f6f44800-7fc5-11e9-8a0e-a2c9a5fd9de4.png)

In fact this situation is _exactly_ what I want. The proposed solution to add /usr/bin` to the backup set is inappropriate. Furthermore, if I click the "Include Folder" button to try and do what it wants me to do, I get an error message:

![Bad message 2](https://user-images.githubusercontent.com/1097249/58387049-1a1ef780-7fc6-11e9-8b23-5c3ff50220c0.png)

If I click the "Exclude Folder" button, the first message re-appears!

All in all it's a somewhat poor user experience.

**Comment by spersson** [comment]
Ah, yes. I obviously had not considered this scenario. I will soon try to take some time for making this a bit more intelligent. Possibly that could also solve (at least to an acceptable level) the problem reported in issue #70 .
Thanks!

**Comment by Pointedstick** [comment]
You're welcome!

**Comment by spersson** [comment]
Resolved by not warning the user in this scenario.

**Comment by Pointedstick** [comment]
:tada:
