### ISSUE TITLE
Include ~/Music and ~/Videos by default

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#73]
Upon setting up a new backup plan, I noticed that `~/Music` and `~/Videos` were not automatically selected in the list of folders to back up. Personally I have a lot of music in my Music folder that I very much want to have backed up, and I had to notice that the location was not included by default and then manually include it. I think including these two folders makes for a better set of default settings.

**Comment by spersson** [comment]
What makes for good default settings is a common bike shedding topic... as I'm sure you are aware. :) I excluded those folders by default based on assuming that they contain big files which are not personal, you would not cry if you lost them. Most of them could probably be downloaded again easily. But it could be that the times have changed... with the rise of spotify and netflix perhaps it is not so common anymore to have those folders full of pirated files. Perhaps people nowadays actually keep more unique and personal items there. I'll change it, this is not a very important setting anyway.

**Comment by Pointedstick** [comment]
I think music and video files are actually the very definition of personal files. I don't have any videos stored personally but I would be heartbroken if I lost all my music. I've accumulated my collection over 15 years, and it represents probably thousands of dollars worth of purchased music. Some of it was downloaded from iTunes and Amazon and Bandcamp et al and could be re-downloaded, but a large fraction came from physical CDs that I don't have anymore. Also re-downloading all the music that came from iTunes would be challenging since I don't own a computer capable of running iTunes anymore.

**Comment by Pointedstick** [comment]
Thank you very much!
