### ISSUE TITLE
When a LUKS-encrypted disk is plugged in while the KCM is open, Plasma displays two prompts to unlock it, and neither one succeeds at unlocking the disk

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#77]
I back up to a LUKS-encrypted disk. When I plug it in, Plasma displays a prompt to enter its password to unlock it. This works fine.

However, when the Kup KCM is already open when I plug in the disk, I get two prompts, one right after the other:

![Screenshot_20190526_160716](https://user-images.githubusercontent.com/1097249/58387699-5bb4a000-7fd0-11e9-9d60-c9c9e447e00e.png)

After I enter my password in the first one, the disk doesn't actually unlock. The devices notifier reports the status as "Accessing":

![Screenshot_20190526_160749](https://user-images.githubusercontent.com/1097249/58387710-79820500-7fd0-11e9-95b8-b0f42378728b.png)

If I enter my password into the second prompt, nothing changes. The disk is not accessible. I need to first plug in and unlock the disk before opening the Kup KCM, and then everything works fine,

**Comment by spersson** [comment]
Sounds like I'm going to have to try this myself, thanks for the report!

**Comment by Pointedstick** [comment]
You're very welcome!

**Comment by spersson** [comment]
I was only getting failures mounting the device sometimes. But regardless of that, if plasma auto-mounting is enabled it looks bad to get two prompts for the same thing. I just disabled mounting encrypted devices from kup now. Not worth it just for showing space info. It will still show the info if the partion is mounted later.

**Comment by Pointedstick** [comment]
Fantastic, thanks!
