### ISSUE TITLE
Exclude Baloo index by default

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#82]
I noticed that Kup was backing up `~/.local/share/baloo/`. This is not necessary as the index in that folder can always be recreated as needed, and including it in the backup set will make it always get re-copied because it changes very frequently.

**Comment by spersson** [comment]
OK, good to know. I will fix that soon.

**Comment by spersson** [comment]
OK, good to know. I will fix that soon.

**Comment by spersson** [comment]
Fixed.
