### ISSUE TITLE
How do you run a manual back-up plan ?

### ISSUE THREAD

**Issue by johnchristopher** [spersson/Kup#84]
I set up a manual back-up for a folder months ago. Clicking on `Save new backup` works as intended.

I remember spending a lot of time (including re-installing kup and diving into bup man page) before finding how.

I remember it was quite idiosyncratic and couldn't find documentation about it, maybe a comment on Reddit or GitHub.

Now months later I want to add another manual back-up plan but I can't find the button in the interface (I got the `this backup plan has never been run` and the red shield).

I can't find the ritual to perform the first manual back-up anymore.

How do I run a manual back-up plan ?

**Comment by spersson** [comment]
You need to use the applet in the systray. The "Save New Backup" button will be available if the backup destination is available.

**Comment by johnchristopher** [comment]
Finally got it last week.

If the destination doesn't exist no button will ever appear. I think it's a significant usability issue. Would you consider adding a warning for a non-existing destination when creating a new back-up plan ?
