### ISSUE TITLE
By default, exclude ~/.local/share/TelegramDesktop/tdata/temp and ~/.config/Riot/Cache/

### ISSUE THREAD

**Issue by Pointedstick** [spersson/Kup#86]
`~/.local/share/TelegramDesktop/tdata/temp` and `~/.config/Riot/Cache/` are temp folders and not anything that it makes sense to back up.

Without excluding these paths, my backups often fail with errors like these:

```
file has vanished: "/home/nate/.config/Riot/Cache/e5adc6e51080dddb_0"
file has vanished: "/home/nate/.local/share/TelegramDesktop/tdata/temp/fde74e0d99c4b392.png"
```

Ideally these apps would respect the XDG directory spec and put their temp ane cache files in `~/.cache`, but they don't. :(

**Comment by spersson** [comment]
Yep, unfortunate. I have added them as default excludes. Thanks!
