### ISSUE TITLE
Kup doesn't enable bup fsck parallelism

### ISSUE THREAD

**Issue by tesfabpel** [spersson/Kup#90]
I was doing a backup today and it's generating restore information for quite a long time and I saw that only one core is being used...
I found out that `bup fsck` accepts `-j` an option to enable parallelism that should (I hope) speed up the process.
I have a CPU with a lot of cores so it's quite sad to see all of them sit idle except one.

**Comment by spersson** [comment]
Excellent idea. I have made a change to use parallell jobs now. It will be part of next release. Thank you!
