### ISSUE TITLE
Failure to backup files that disappared between `bup index` & `bup save` treated as fatal

### ISSUE THREAD

**Issue by alexander255** [spersson/Kup#91]
When backing up my home directory there is a 70%+ chance that `kup` will treat that whole `bup`-based backup as failure, because some individual files disappeared between `bub index` and `bub save`:

> Kup is starting bup backup job at Dienstag, 19. November 2019 15:04:57 CET
> 
> bup "-d" "<backup_dir>" "init"
> bup "-d" "<backup_dir>" "index" "-u" …
> bup "-d" "<backup_dir>" "save" "-n" "kup" "-vv" "<source_dir>"
> [Errno 2] No such file or directory: <source_dir>/.mozilla/firefox/Alexander/storage/default/moz-extension+++d9a0de4c-3431-48f2-b841-803e5e6faa62^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.sqlite-wal'
> [Errno 2] No such file or directory: '<source_dir>/.mozilla/firefox/Alexander/storage/default/moz-extension+++39be73b0-c9c8-483f-9fee-740b75df8edd^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.sqlite-wal'
> WARNING: 3 errors encountered while saving.
>
> Kup did not successfully complete the bup backup job: failed to save everything.

While `bup` does correctly report these conditions as just a *WARNING* it probably returns a non-zero exit status which `kup`'s task runner then considers fatal?

Ideally `kup` would not just detect this condition but actually collect the list of single file failures and report it at the end of the backup in some summary report. The current state, IMHO, makes the *check integrity* and *generate recovery information* advanced checkboxes fairly useless as their corresponding commands will hardly ever be run.

**Comment by Uatschitchun** [comment]
Noticed the same. It could be some tmp files only or other irrelevant files that changed or were removed during the backup process. To prevent this, I have to be sure to not be using my laptop during the backup and so reduces the amount of backups I do ;(
Would be nice to have a solution here!

**Comment by spersson** [comment]
Yep, it was time to do something about this one. Fixed in https://invent.kde.org/kde/kup/-/commit/9eea1ff1462c20f92a1a3bec048aa749028873e3
