### ISSUE TITLE
[bup] Allow setting file extension and custom regexp ignore patterns

### ISSUE THREAD

**Issue by alexander255** [spersson/Kup#92]
Currently one can only blacklist whole directories in *Kup*, but `bup` itself also supports custom regexp ignore patterns.

The most important ignore patterns I can think of in this regard would be:

  * In-flight sqlite database transactions: `*.sqlite-wal` (“write ahead log”).
  * Text editor temp files: `*.kate-swp`, `*.goutputstream-*`, …
  * Backup files: `*~` & `*.bak`

Since the above can and have been all be described using fnmatch/glob patterns limiting it to the fnmatch syntax supported by `rsync` would probably be acceptable and enable sharing the pattern list between `bup` and `rsync` based backups.

**Comment by spersson** [comment]
yep, I have been thinking of doing something like this for a while. It's been discussed here before. I have not yet had the time or motivation to hammer out a design. I'm thinking of always specfying what to backup as a list of rules, and the current folder selection can be a simple view onto those rules. Then a rule can be simple include or exclude folder or it could be pattern based.

**Comment by spersson** [comment]
I ended up doing a simpler design (better to do a simple solution than to dream about a fancy one). So now you can point to a text file with patterns for both bup and rsync backups.
![image](https://user-images.githubusercontent.com/1425156/77820171-30806d00-711b-11ea-96e6-d162ed3f625d.png)
https://invent.kde.org/kde/kup/-/commit/293a7eb607801e5cc777730e6b79176b8404d282
