### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by Uatschitchun** [spersson/Kup#93]
As there are some commits sinces last release, is there a new release planned?

**Comment by Sparsa** [comment]
Is this project is abandoned?

**Comment by spersson** [comment]
A new release will come, at least sometime this year... that's all I dare to commit to... And the project is in the process of moving to KDE infrastructure so the latest code changes are only there. This place is still easier for some people to raise issues and discuss so I'll keep it around for now.
