### ISSUE TITLE
The name Kup conflicts with (Kup "Kernel Uploader")

### ISSUE THREAD

**Issue by Jam3alay8** [spersson/Kup#94]
I am running Fedora. Fedora has a package by the name "Kup" (Kernel Uploader).
Please consider renaming Kup  to avoid the name conflict.
I have found this package "kup-0.7.3-1.1.x86_64.rpm" and I was able to install it in my Fedora 31 KDE. However there is the kernel uploader (kup) also listed.

**Comment by spersson** [comment]
Yes, I became aware of this name clash when the debian packager named the package there kup-backup. I doubt anybody will get confused about which one you mean, so it's mostly a technical issue of packaging systems... which can be solved like in Debian. That said, I don't have strong feelings about the name. It's mostly that it already has become known under this name and my motivation for changing is low. Thanks for bringing it up, showing that you care. And feel free to suggest a new name, you never know what could happen...! :)
