### ISSUE TITLE
No Kup icon in the tray area

### ISSUE THREAD

**Issue by carlonluca** [spersson/Kup#95]
Hello,
while developing for #10, I installed a newer version of kup from the git repo. Since then, I cannot see the Kup icon in the tray anymore. I tried to downgrade, I tried the version from the Kubuntu repo, I tried to run the daemon from the terminal but I can see no clear error. I also tried to clear my plans, create new plans, remove the Kup configuration entirely from ~/.config/kuprc but nothing restored the icon. I see Kup in the system tray settings list, but does not show up.
Any idea what may be messed up? Is there anything else that may remain after "make uninstall" and apt purge?
Thank you.
Regards.

**Comment by spersson** [comment]
It's by design not visible if the kup-daemon is not running. Kup daemon will autostart on login (if backups are enabled in settings) or when settings are saved and backups have been enabled and it's not already running.

You can check if the following service is up on your session dbus: org.kde.kupdaemon

**Comment by carlonluca** [comment]
Hello, thank you for your answer. The kup-daemon process is running, and the service org.kde.kupdaemon is listed by qdbusviewer. Still no Kup icon though. Anything else I can check?

**Comment by spersson** [comment]
Just to be sure... you know it's hidden by default, right? So click the little arrow and it should be there.

then the following files should be installed:
```
/usr/share/plasma/plasmoids/org.kde.kupapplet/contents/ui/FullRepresentation.qml
/usr/share/plasma/plasmoids/org.kde.kupapplet/contents/ui/Main.qml
/usr/share/plasma/plasmoids/org.kde.kupapplet/metadata.desktop
```

I think the plasmoid should show up in systray even if the "backups" data engine doesn't work, but it's easy to confirm by running the "plasma engine explorer" .

**Comment by carlonluca** [comment]
Yes, I know it may be hidden, but it is not even in the other menu.
Yes, those files seem to be in place.
I see this in the plasma engine explorer:

![Screenshot_20200415_080052](https://user-images.githubusercontent.com/3678828/79303494-536a9980-7eef-11ea-9ebe-aa989c29a23f.png)

Do you know if I can somehow debug the dataengine? I do not see a connection to the kup-daemon- socket after starting the daemon, but I suspect I should get a connection, right? The connection arrives when I open the plasma engine explorer.

**Comment by carlonluca** [comment]
I probably found the problem. It seems something remained in /usr/local/share/plasma/plasmoids from a previous installation. Thanks for your help!
